<?xml version="1.0" encoding="utf-8"?>
<TestRecord xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <Tests>
    <TestRecord Name="ArtekSoftware">
      <Tests>
        <TestRecord Name="Conference">
          <Tests>
            <TestRecord Name="RemoteData">
              <Tests>
                <TestRecord Name="Tests">
                  <Tests>
                    <TestRecord Name="Integration">
                      <Tests>
                        <TestRecord Name="SessionTests">
                          <Results>
                            <UnitTestResult>
                              <TestDate>2012-05-02T21:14:53</TestDate>
                              <Passed>0</Passed>
                              <Errors>3</Errors>
                              <Failures>0</Failures>
                              <Inconclusive>0</Inconclusive>
                              <NotRunnable>0</NotRunnable>
                              <Skipped>0</Skipped>
                              <Ignored>4</Ignored>
                              <Time />
                              <Message>One or more child tests had errors</Message>
                            </UnitTestResult>
                          </Results>
                          <Tests>
                            <TestRecord Name="sessions_should_return_valid_data">
                              <Results>
                                <UnitTestResult>
                                  <TestDate>2012-05-02T21:14:53</TestDate>
                                  <Passed>0</Passed>
                                  <Errors>1</Errors>
                                  <Failures>0</Failures>
                                  <Inconclusive>0</Inconclusive>
                                  <NotRunnable>0</NotRunnable>
                                  <Skipped>0</Skipped>
                                  <Ignored>0</Ignored>
                                  <Time />
                                  <Message>System.TypeLoadException : A type load exception has occurred.</Message>
                                  <StackTrace>  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&amp;)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in &lt;filename unknown&gt;:0 </StackTrace>
                                  <ConsoleOutput />
                                  <ConsoleError />
                                </UnitTestResult>
                                <UnitTestResult>
                                  <TestDate>2012-05-02T21:15:13</TestDate>
                                  <Passed>0</Passed>
                                  <Errors>1</Errors>
                                  <Failures>0</Failures>
                                  <Inconclusive>0</Inconclusive>
                                  <NotRunnable>0</NotRunnable>
                                  <Skipped>0</Skipped>
                                  <Ignored>0</Ignored>
                                  <Time />
                                  <Message>System.TypeLoadException : A type load exception has occurred.</Message>
                                  <StackTrace>  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&amp;)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in &lt;filename unknown&gt;:0 </StackTrace>
                                  <ConsoleOutput />
                                  <ConsoleError />
                                </UnitTestResult>
                                <UnitTestResult>
                                  <TestDate>2012-05-02T21:15:31</TestDate>
                                  <Passed>0</Passed>
                                  <Errors>1</Errors>
                                  <Failures>0</Failures>
                                  <Inconclusive>0</Inconclusive>
                                  <NotRunnable>0</NotRunnable>
                                  <Skipped>0</Skipped>
                                  <Ignored>0</Ignored>
                                  <Time />
                                  <Message>System.TypeLoadException : A type load exception has occurred.</Message>
                                  <StackTrace>  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&amp;)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in &lt;filename unknown&gt;:0 </StackTrace>
                                  <ConsoleOutput />
                                  <ConsoleError />
                                </UnitTestResult>
                                <UnitTestResult>
                                  <TestDate>2012-05-02T21:16:35</TestDate>
                                  <Passed>0</Passed>
                                  <Errors>1</Errors>
                                  <Failures>0</Failures>
                                  <Inconclusive>0</Inconclusive>
                                  <NotRunnable>0</NotRunnable>
                                  <Skipped>0</Skipped>
                                  <Ignored>0</Ignored>
                                  <Time />
                                  <Message>System.TypeLoadException : A type load exception has occurred.</Message>
                                  <StackTrace>  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&amp;)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in &lt;filename unknown&gt;:0 </StackTrace>
                                  <ConsoleOutput />
                                  <ConsoleError />
                                </UnitTestResult>
                              </Results>
                            </TestRecord>
                            <TestRecord Name="should_create_new_session">
                              <Results>
                                <UnitTestResult>
                                  <TestDate>2012-05-02T21:14:53</TestDate>
                                  <Passed>0</Passed>
                                  <Errors>1</Errors>
                                  <Failures>0</Failures>
                                  <Inconclusive>0</Inconclusive>
                                  <NotRunnable>0</NotRunnable>
                                  <Skipped>0</Skipped>
                                  <Ignored>0</Ignored>
                                  <Time />
                                  <Message>System.TypeLoadException : A type load exception has occurred.</Message>
                                  <StackTrace>  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&amp;)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in &lt;filename unknown&gt;:0 </StackTrace>
                                  <ConsoleOutput />
                                  <ConsoleError />
                                </UnitTestResult>
                              </Results>
                            </TestRecord>
                            <TestRecord Name="should_create_new_session_with_put">
                              <Results>
                                <UnitTestResult>
                                  <TestDate>2012-05-02T21:14:53</TestDate>
                                  <Passed>0</Passed>
                                  <Errors>0</Errors>
                                  <Failures>0</Failures>
                                  <Inconclusive>0</Inconclusive>
                                  <NotRunnable>0</NotRunnable>
                                  <Skipped>0</Skipped>
                                  <Ignored>1</Ignored>
                                  <Time />
                                  <Message>Test ignored</Message>
                                  <ConsoleOutput />
                                  <ConsoleError />
                                </UnitTestResult>
                              </Results>
                            </TestRecord>
                            <TestRecord Name="should_delete_session">
                              <Results>
                                <UnitTestResult>
                                  <TestDate>2012-05-02T21:14:53</TestDate>
                                  <Passed>0</Passed>
                                  <Errors>0</Errors>
                                  <Failures>0</Failures>
                                  <Inconclusive>0</Inconclusive>
                                  <NotRunnable>0</NotRunnable>
                                  <Skipped>0</Skipped>
                                  <Ignored>1</Ignored>
                                  <Time />
                                  <Message>Test ignored</Message>
                                  <ConsoleOutput />
                                  <ConsoleError />
                                </UnitTestResult>
                              </Results>
                            </TestRecord>
                            <TestRecord Name="should_get_single_session">
                              <Results>
                                <UnitTestResult>
                                  <TestDate>2012-05-02T21:14:53</TestDate>
                                  <Passed>0</Passed>
                                  <Errors>1</Errors>
                                  <Failures>0</Failures>
                                  <Inconclusive>0</Inconclusive>
                                  <NotRunnable>0</NotRunnable>
                                  <Skipped>0</Skipped>
                                  <Ignored>0</Ignored>
                                  <Time />
                                  <Message>System.TypeLoadException : A type load exception has occurred.</Message>
                                  <StackTrace>  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&amp;)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in &lt;filename unknown&gt;:0 </StackTrace>
                                  <ConsoleOutput />
                                  <ConsoleError />
                                </UnitTestResult>
                              </Results>
                            </TestRecord>
                            <TestRecord Name="should_not_be_able_to_post_to_existing_session">
                              <Results>
                                <UnitTestResult>
                                  <TestDate>2012-05-02T21:14:53</TestDate>
                                  <Passed>0</Passed>
                                  <Errors>0</Errors>
                                  <Failures>0</Failures>
                                  <Inconclusive>0</Inconclusive>
                                  <NotRunnable>0</NotRunnable>
                                  <Skipped>0</Skipped>
                                  <Ignored>1</Ignored>
                                  <Time />
                                  <Message>Test ignored</Message>
                                  <ConsoleOutput />
                                  <ConsoleError />
                                </UnitTestResult>
                              </Results>
                            </TestRecord>
                            <TestRecord Name="should_update_existing_session_with_put">
                              <Results>
                                <UnitTestResult>
                                  <TestDate>2012-05-02T21:14:53</TestDate>
                                  <Passed>0</Passed>
                                  <Errors>0</Errors>
                                  <Failures>0</Failures>
                                  <Inconclusive>0</Inconclusive>
                                  <NotRunnable>0</NotRunnable>
                                  <Skipped>0</Skipped>
                                  <Ignored>1</Ignored>
                                  <Time />
                                  <Message>Test ignored</Message>
                                  <ConsoleOutput />
                                  <ConsoleError />
                                </UnitTestResult>
                              </Results>
                            </TestRecord>
                          </Tests>
                        </TestRecord>
                      </Tests>
                    </TestRecord>
                  </Tests>
                </TestRecord>
              </Tests>
            </TestRecord>
          </Tests>
        </TestRecord>
      </Tests>
    </TestRecord>
  </Tests>
</TestRecord>